version: '3.0'

services:
  # postgres-db:
  #     restart: always
  #     ports:
  #         - '5432:5432'
  #     image: kiasaki/alpine-postgres:9.5
  #     hostname: shop-db
  #     environment:
  #         POSTGRES_PASSWORD: psql123
  #         POSTGRES_USER: postgres
  #         POSTGRES_DB: shop
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
      - "6477:6477"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*



