apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.moduleName }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: {{ .Values.workloadSelector }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: {{ .Values.workloadSelector }}
    spec:
      affinity: {}
      containers:
      - name: {{ .Values.moduleName }}
        image: {{ .Values.artifactoryUrl }}/{{ .Values.moduleName }}:{{ .Values.version }}
        imagePullPolicy: Always
        env:
        - name: RELEASE_TIME
          value: {{.Release.Time}}
        - name: product-db-host
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap }}
              key: product-db-host
        - name: product-service-port
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap }}
              key: product-service-port
        - name: product-db-user
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets }}
              key: product-db-user
        - name: product-db-password
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets }}
              key: product-db-password
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
