apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moduleName }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  selector:
    workload.user.cattle.io/workloadselector: {{ .Values.workloadSelector }}
  sessionAffinity: None
  type: ClusterIP
