moduleName: config-map

# The following should be considered default values, and will be overridden by Jenkinsfile
namespace: singleshop-dev
tcloudDomain: main.tcloud.kpn.org
secrets: singleshop-secrets
configMap: singleshop-config
artifactoryUrl: artifacts.kpn.org/ecommerce
version: latest
